#+TITLE: Emacs Config 
#+AUTHOR: Raian Tasfin
#+EMAIL: raian.csecu@gmail.com
#+OPTIONS: num:nil

To turn any feature on/off comment/uncomment the section. The key
binding for toggling org mode section comments is `C-;'.

* Major Modes
  :PROPERTIES:
  :CUSTOM_ID: major-modes
  :END:
** Org Mode
   :PROPERTIES:
   :CUSTOM_ID: org-mode
   :END:
   Minor options for org mode.
*** org-num-mode
    :PROPERTIES:
    :CUSTOM_ID: org-num-mode
    :END:
    Show section numbers in org mode by default.
    #+BEGIN_SRC emacs-lisp
    (add-hook 'org-mode-hook #'org-num-mode)
    #+END_SRC
** C Mode
   :PROPERTIES:
   :CUSTOM_ID: c-mode
   :END:
*** Indentation
    :PROPERTIES:
    :CUSTOM_ID: indentation
    :END:
    #+BEGIN_SRC emacs-lisp
    (setq-default c-basic-offset 4)
    #+END_SRC
* Default Emacs Options
  :PROPERTIES:
  :CUSTOM_ID: default-emacs-options
  :END:
  #+BEGIN_SRC emacs-lisp
  (setq auto-save-file-name-transforms
    `((".*" ,temporary-file-directory t)))
  #+END_SRC

* Appearance
  :PROPERTIES:
  :CUSTOM_ID: appearance
  :END:
** Start Message
   :PROPERTIES:
   :CUSTOM_ID: start-message
   :END:
   Hide the starting message message
   
   #+BEGIN_SRC emacs-lisp
   (setq inhibit-startup-message t)
   #+END_SRC
** COMMENT Scratch Message
   For now I want the default scratch message to signal that emacs has
   been loaded successfully and we are on the scratch buffer.
   
   #+BEGIN_SRC emacs-lisp 
   (setq initial-scratch-message nil)
   #+END_SRC

** Tool Bar
   :PROPERTIES:
   :CUSTOM_ID: tool-bar
   :END:
   Hide graphic tool bar
   #+BEGIN_SRC emacs-lisp 
   (tool-bar-mode -1)
   #+END_SRC

** Menu Bar
   :PROPERTIES:
   :CUSTOM_ID: menu-bar
   :END:
   Hide graphic menu bar
   #+BEGIN_SRC emacs-lisp 
   (menu-bar-mode -1)
   #+END_SRC
   
** Typeface and Font
   :PROPERTIES:
   :CUSTOM_ID: typeface-and-font
   :END:
   #+BEGIN_SRC emacs-lisp
   (set-frame-font "Fira Code-11.5" nil t)
   #+END_SRC

** Line Numbering
   :PROPERTIES:
   :CUSTOM_ID: line-numbering
   :END:
   #+BEGIN_SRC emacs-lisp
   (setq display-line-numbers-type 'relative)
   (global-display-line-numbers-mode)
   #+END_SRC

** Theme
   :PROPERTIES:
   :CUSTOM_ID: theme
   :END:
   To enable or disable any option, comment or uncomment that section
   respectively. The current shortcut for toggling comments is C-;
   . For confirmation, see 

*** modus-operandi-tinted
    :PROPERTIES:
    :CUSTOM_ID: modus-operandi-tinted
    :END:

    A modus light tinted theme. The default right now.
    #+BEGIN_SRC emacs-lisp
    (use-package modus-themes
      :config
      (load-theme 'modus-operandi-tinted t))
    #+End_SRC

*** COMMENT modus-vivendi-tinted
    A modus light tinted theme. The default right now.
    #+BEGIN_SRC emacs-lisp
    (use-package modus-themes
      :config
      (load-theme 'modus-vivendi-tinted t))
    #+END_SRC

*** COMMENT base16-gruvbox-dark-medium
    Preferred default dark theme
    #+BEGIN_SRC emacs-lisp
    (use-package base16-theme
      :config
      (load-theme 'base16-gruvbox-dark-medium t))
    #+END_SRC

*** COMMENT leuven
    Reliable light theme. Suitable in screens where modus-operandi
    tinted is a bit too warm.
    #+BEGIN_SRC emacs-lisp
    (use-package leuven-theme
      :config
      (load-theme 'leuven t))
    #+END_SRC

   To Use any of the themes, I have to just uncomment the config line
   of it and comment the configs for other themes.

** Spaceline
   :PROPERTIES:
   :CUSTOM_ID: spaceline
   :END:
   Ripped off the internet 

   #+BEGIN_SRC emacs-lisp
   (use-package spaceline
     :config
     (spaceline-spacemacs-theme)
     (spaceline-toggle-minor-modes-off)
     (spaceline-toggle-buffer-encoding-off)
     (spaceline-toggle-buffer-encoding-abbrev-off)
     (setq spaceline-highlight-face-func 
       'spaceline-highlight-face-evil-state)
     (spaceline-define-segment line-column
       "The current line and column numbers."
       "l:%l c:%2c")
     (spaceline-define-segment time
       "The current time."
       (format-time-string "%H:%M"))
     (spaceline-define-segment date
       "The current date."
       (format-time-string "%h %d"))
     (spaceline-toggle-time-on)
     (spaceline-emacs-theme 'date 'time))
   #+END_SRC

* Editing
  :PROPERTIES:
  :CUSTOM_ID: editing
  :END:
** Default Indentation
   :PROPERTIES:
   :CUSTOM_ID: default-indentation
   :END:
   #+BEGIN_SRC emacs-lisp
   (setq default-tab-width 4)
   #+END_SRC
** Small Default Configs
   :PROPERTIES:
   :CUSTOM_ID: small-default-configs
   :END:
*** Auto Fill Mode
    :PROPERTIES:
    :CUSTOM_ID: auto-fill-mode
    :END:
    #+BEGIN_SRC emacs-lisp
    (setq-default auto-fill-function 'do-auto-fill)
    #+END_SRC
*** Electric Pair Mode
    :PROPERTIES:
    :CUSTOM_ID: electric-pair-mode
    :END:
    Match parenthesis.
    #+BEGIN_SRC emacs-lisp
    (electric-pair-mode 1)
    #+END_SRC
*** Fly-Spell Enabled by Default
    :PROPERTIES:
    :CUSTOM_ID: fly-spell-enabled-by-default
    :END:
    #+BEGIN_SRC emacs-lisp
    (dolist (hook '(text-mode-hook))
      (add-hook hook (lambda () (flyspell-mode 1))))
    #+END_SRC
